//! The damage model (`docs/02` §8).
//!
//! ```text
//! damage = max(1, (attack × elevation_modifier) − armour_of_matching_type + bonus_vs_class)
//! ```
//!
//! A pure function of static kind data, the two players' modifiers and the
//! ground, so it is testable without a match and can be printed as the
//! damage matrix committed at `docs/damage-matrix.md`. Who hits whom, when,
//! and what a hit looks like are the order machines' business; this module
//! only answers "how much".

use crate::kinds::{self, Class, Combat, DamageType, KindInfo};
use crate::orders::Modifiers;

/// Where the attacker stands relative to the target (`GD-COMBAT-03`).
#[derive(Clone, Copy, PartialEq, Eq, Debug, Default)]
pub enum Elevation {
    /// Same level.
    #[default]
    Level,
    /// The attacker is higher: five quarters of the attack.
    Downhill,
    /// The attacker is lower: three quarters of the attack.
    Uphill,
}

impl Elevation {
    /// From the two tiles' elevation levels.
    pub const fn between(attacker: u8, target: u8) -> Elevation {
        if attacker > target {
            Elevation::Downhill
        } else if attacker < target {
            Elevation::Uphill
        } else {
            Elevation::Level
        }
    }

    /// The attack after the modifier, rounded to nearest, halves up.
    pub const fn apply(self, attack: i32) -> i32 {
        match self {
            Elevation::Level => attack,
            Elevation::Downhill => (attack * 5 + 2) / 4,
            Elevation::Uphill => (attack * 3 + 2) / 4,
        }
    }
}

/// Armour against each damage type.
#[derive(Clone, Copy, PartialEq, Eq, Debug, Default)]
pub struct Armour {
    /// Against melee hits.
    pub melee: i32,
    /// Against pierce hits.
    pub pierce: i32,
}

impl Armour {
    /// The armour a hit of `kind` meets. Siege meets none (`GD-COMBAT-01`).
    pub const fn against(self, kind: DamageType) -> i32 {
        match kind {
            DamageType::Melee => self.melee,
            DamageType::Pierce => self.pierce,
            DamageType::Siege => 0,
        }
    }
}

/// One hit's worth of damage, never below 1 (`GD-COMBAT-05`).
pub const fn damage(
    attack: i32,
    kind: DamageType,
    elevation: Elevation,
    armour: Armour,
    bonus: i32,
) -> i32 {
    let d = elevation.apply(attack) - armour.against(kind) + bonus;
    if d < 1 {
        1
    } else {
        d
    }
}

/// True if a hit of this type also lands on the attacker's own side when
/// they are in the way (`GD-COMBAT-04`): siege makes no distinction.
pub const fn hits_friends(kind: DamageType) -> bool {
    matches!(kind, DamageType::Siege)
}

/// The bonus an attacker's kind carries against a class.
pub fn bonus_vs(attacker: &Combat, class: Class) -> i32 {
    attacker
        .bonuses
        .iter()
        .filter(|(c, _)| *c == class)
        .map(|(_, b)| *b)
        .sum()
}

/// A kind's attack after its owner's technologies.
pub fn attack_of(k: &KindInfo, mods: &Modifiers) -> i32 {
    if k.combat.attack == 0 {
        0
    } else {
        k.combat.attack + mods.attack_bonus[k.class.index()]
    }
}

/// A kind's armour after its owner's technologies.
pub fn armour_of(k: &KindInfo, mods: &Modifiers) -> Armour {
    Armour {
        melee: k.combat.melee_armour + mods.melee_armour_bonus[k.class.index()],
        pierce: k.combat.pierce_armour + mods.pierce_armour_bonus[k.class.index()],
    }
}

/// A kind's reach in tiles after its owner's technologies; 0 is hand to hand.
pub fn range_of(k: &KindInfo, mods: &Modifiers) -> i32 {
    if k.combat.attack == 0 || k.combat.range == 0 {
        k.combat.range
    } else {
        (k.combat.range + mods.range_bonus[k.class.index()]).max(1)
    }
}

/// Damage one kind does to another per hit, with both owners' technologies
/// and the ground taken into account. `None` if the attacker cannot fight
/// or the target is not something that takes hits.
pub fn between(
    attacker: &KindInfo,
    attacker_mods: &Modifiers,
    target: &KindInfo,
    target_mods: &Modifiers,
    elevation: Elevation,
) -> Option<i32> {
    if attacker.combat.attack == 0 || target.class == Class::Other {
        return None;
    }
    Some(damage(
        attack_of(attacker, attacker_mods),
        attacker.combat.damage,
        elevation,
        armour_of(target, target_mods),
        bonus_vs(&attacker.combat, target.class),
    ))
}

/// The kinds that fight, in table order: the rows and columns of the matrix.
pub fn fighters() -> impl Iterator<Item = &'static KindInfo> {
    kinds::all()
        .iter()
        .filter(|k| k.combat.attack > 0 && k.mobile)
}

/// The damage matrix as a Markdown document: every fighting kind against
/// every fighting kind and every building, on level ground with no
/// technology, plus the elevation rows. Generated by `simrunner matrix`
/// and committed, so a change to the numbers is a change in the diff.
pub fn matrix_markdown() -> String {
    use std::fmt::Write;
    let base = Modifiers::default();
    let rows: Vec<&KindInfo> = fighters().collect();
    let cols: Vec<&KindInfo> = kinds::all()
        .iter()
        .filter(|k| (k.combat.attack > 0 && k.mobile) || k.class == Class::Building)
        .collect();
    let mut out = String::new();
    let _ = writeln!(out, "# Damage matrix");
    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "Generated from the kinds table by the command below; `scripts/check-generated.sh` \
         fails if this file drifts from it. Do not edit by hand."
    );
    let _ = writeln!(out);
    let _ = writeln!(out, "```sh");
    let _ = writeln!(
        out,
        "cargo run -p simrunner -- matrix --out docs/damage-matrix.md"
    );
    let _ = writeln!(out, "```");
    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "The rule (`docs/02` §8, `GD-COMBAT-01` to `GD-COMBAT-05`):"
    );
    let _ = writeln!(out);
    let _ = writeln!(out, "```text");
    let _ = writeln!(
        out,
        "damage = max(1, (attack × elevation) − armour_of_matching_type + bonus_vs_class)"
    );
    let _ = writeln!(out, "```");
    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "Elevation is five quarters of the attack downhill and three quarters uphill, \
         rounded to nearest with halves up. Melee hits meet melee armour, pierce hits meet \
         pierce armour, siege hits meet no armour and land on friends in the way too. \
         Nothing does less than 1."
    );
    let _ = writeln!(out);
    let _ = writeln!(out, "## Kinds");
    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "| Kind | Class | HP | Attack | Range | Armour (melee/pierce) | Bonus |"
    );
    let _ = writeln!(out, "|---|---|---|---|---|---|---|");
    for k in &cols {
        let c = &k.combat;
        let bonus = if c.bonuses.is_empty() {
            "—".to_string()
        } else {
            c.bonuses
                .iter()
                .map(|(cl, b)| format!("+{b} vs {}", cl.plural()))
                .collect::<Vec<_>>()
                .join(", ")
        };
        let attack = if c.attack == 0 {
            "—".to_string()
        } else {
            format!("{} {}", c.attack, c.damage.name())
        };
        let range = if c.attack == 0 {
            "—".to_string()
        } else if c.range == 0 {
            "hand".to_string()
        } else {
            c.range.to_string()
        };
        let _ = writeln!(
            out,
            "| {} | {} | {} | {} | {} | {}/{} | {} |",
            k.name,
            k.class.plural(),
            k.max_health,
            attack,
            range,
            c.melee_armour,
            c.pierce_armour,
            bonus
        );
    }
    let _ = writeln!(out);
    let _ = writeln!(out, "## Damage per hit, level ground, no technology");
    let _ = writeln!(out);
    let _ = writeln!(out, "Rows attack columns.");
    let _ = writeln!(out);
    let mut header = String::from("| Attacker \\ Target |");
    let mut rule = String::from("|---|");
    for k in &cols {
        let _ = write!(header, " {} |", k.name);
        rule.push_str("---|");
    }
    let _ = writeln!(out, "{header}");
    let _ = writeln!(out, "{rule}");
    for a in &rows {
        let mut line = format!("| **{}** |", a.name);
        for t in &cols {
            let d = between(a, &base, t, &base, Elevation::Level).unwrap_or(0);
            let _ = write!(line, " {d} |");
        }
        let _ = writeln!(out, "{line}");
    }
    let _ = writeln!(out);
    let _ = writeln!(out, "## Hits to kill, level ground, no technology");
    let _ = writeln!(out);
    let _ = writeln!(out, "{header}");
    let _ = writeln!(out, "{rule}");
    for a in &rows {
        let mut line = format!("| **{}** |", a.name);
        for t in &cols {
            let d = between(a, &base, t, &base, Elevation::Level).unwrap_or(1);
            let hits = (t.max_health + d - 1) / d;
            let _ = write!(line, " {hits} |");
        }
        let _ = writeln!(out, "{line}");
    }
    let _ = writeln!(out);
    let _ = writeln!(out, "## Elevation");
    let _ = writeln!(out);
    let _ = writeln!(out, "Each fighter's attack against no armour, by ground.");
    let _ = writeln!(out);
    let _ = writeln!(out, "| Attacker | Uphill | Level | Downhill |");
    let _ = writeln!(out, "|---|---|---|---|");
    for a in &rows {
        let at = |e: Elevation| damage(a.combat.attack, a.combat.damage, e, Armour::default(), 0);
        let _ = writeln!(
            out,
            "| {} | {} | {} | {} |",
            a.name,
            at(Elevation::Uphill),
            at(Elevation::Level),
            at(Elevation::Downhill)
        );
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    /// REQ: GD-COMBAT-01
    #[test]
    fn each_damage_type_meets_its_own_armour() {
        let a = Armour {
            melee: 3,
            pierce: 1,
        };
        assert_eq!(damage(10, DamageType::Melee, Elevation::Level, a, 0), 7);
        assert_eq!(damage(10, DamageType::Pierce, Elevation::Level, a, 0), 9);
        assert_eq!(damage(10, DamageType::Siege, Elevation::Level, a, 0), 10);
    }

    /// REQ: GD-COMBAT-02
    #[test]
    fn class_bonuses_are_the_counters() {
        let spear = kinds::info(kinds::SPEARMAN);
        let sling = kinds::info(kinds::SLINGER);
        let cav = kinds::info(kinds::LIGHT_CAVALRY);
        let club = kinds::info(kinds::CLUBMAN);
        let m = Modifiers::default();
        assert_eq!(bonus_vs(&spear.combat, Class::Cavalry), 6);
        assert_eq!(bonus_vs(&spear.combat, Class::Infantry), 0);
        // Spearman: 4 + 6 against cavalry; 4 against infantry.
        assert_eq!(between(spear, &m, cav, &m, Elevation::Level), Some(10));
        assert_eq!(between(spear, &m, club, &m, Elevation::Level), Some(4));
        // Slinger: 4 + 4 against infantry.
        assert_eq!(between(sling, &m, club, &m, Elevation::Level), Some(8));
        assert_eq!(between(sling, &m, cav, &m, Elevation::Level), Some(4));
        // The spearman's pierce armour takes one off a bowman's arrow.
        let bow = kinds::info(kinds::BOWMAN);
        assert_eq!(between(bow, &m, spear, &m, Elevation::Level), Some(4));
        assert_eq!(between(bow, &m, club, &m, Elevation::Level), Some(5));
    }

    /// REQ: GD-COMBAT-03
    #[test]
    fn elevation_scales_the_attack_before_armour() {
        assert_eq!(Elevation::between(2, 1), Elevation::Downhill);
        assert_eq!(Elevation::between(1, 2), Elevation::Uphill);
        assert_eq!(Elevation::between(1, 1), Elevation::Level);
        assert_eq!(Elevation::Downhill.apply(8), 10);
        assert_eq!(Elevation::Uphill.apply(8), 6);
        assert_eq!(
            Elevation::Downhill.apply(3),
            4,
            "three and three quarters rounds up"
        );
        assert_eq!(
            Elevation::Uphill.apply(3),
            2,
            "two and a quarter rounds down"
        );
        let a = Armour {
            melee: 2,
            pierce: 0,
        };
        assert_eq!(damage(8, DamageType::Melee, Elevation::Downhill, a, 0), 8);
        assert_eq!(damage(8, DamageType::Melee, Elevation::Uphill, a, 0), 4);
    }

    /// REQ: GD-COMBAT-04
    #[test]
    fn siege_hits_friends_and_nothing_else_does() {
        assert!(hits_friends(DamageType::Siege));
        assert!(!hits_friends(DamageType::Melee));
        assert!(!hits_friends(DamageType::Pierce));
        for k in kinds::all() {
            if k.combat.damage == DamageType::Siege {
                assert_eq!(k.class, Class::Siege, "{}: only siege fires siege", k.name);
            }
        }
    }

    /// REQ: GD-COMBAT-05
    #[test]
    fn nothing_does_less_than_one() {
        let a = Armour {
            melee: 50,
            pierce: 50,
        };
        assert_eq!(damage(3, DamageType::Melee, Elevation::Uphill, a, 0), 1);
        assert_eq!(damage(0, DamageType::Pierce, Elevation::Level, a, -5), 1);
        let m = Modifiers::default();
        for a in fighters() {
            for t in kinds::all() {
                if let Some(d) = between(a, &m, t, &m, Elevation::Uphill) {
                    assert!(d >= 1, "{} vs {}", a.name, t.name);
                }
            }
        }
    }

    #[test]
    fn technology_folds_into_attack_armour_and_range() {
        let mut m = Modifiers::default();
        m.attack_bonus[Class::Infantry.index()] = 2;
        m.melee_armour_bonus[Class::Infantry.index()] = 1;
        m.pierce_armour_bonus[Class::Infantry.index()] = 1;
        m.range_bonus[Class::Ranged.index()] = 1;
        let club = kinds::info(kinds::CLUBMAN);
        let bow = kinds::info(kinds::BOWMAN);
        assert_eq!(attack_of(club, &m), 5);
        assert_eq!(
            armour_of(club, &m),
            Armour {
                melee: 1,
                pierce: 1
            }
        );
        assert_eq!(range_of(bow, &m), 6);
        assert_eq!(range_of(club, &m), 0, "hand to hand stays hand to hand");
        let tree = kinds::info(kinds::TREE);
        assert_eq!(attack_of(tree, &m), 0);
        assert_eq!(between(tree, &m, club, &m, Elevation::Level), None);
        assert_eq!(between(club, &m, tree, &m, Elevation::Level), None);
        // Bonus damage is not reduced by the extra armour twice.
        let base = Modifiers::default();
        assert_eq!(between(bow, &base, club, &m, Elevation::Level), Some(4));
    }

    #[test]
    fn the_matrix_names_every_fighter_and_every_building() {
        let md = matrix_markdown();
        for k in kinds::all() {
            if k.combat.attack > 0 || k.class == Class::Building {
                assert!(md.contains(k.name), "{} missing", k.name);
            }
        }
        assert!(!md.contains("Tree"));
        assert!(md.contains("| **Spearman** |"));
    }
}
